=== nmaier/mkvtoolnix/examples/matroskasegmentinfo.dtd
<!ELEMENT Info (
          SegmentUID?,
          NextSegmentUID?,
          PreviousSegmentUID?,
          SegmentFamily?,
          SegmentFilename?,
          NextSegmentFilename?,
          PreviousSegmentFilename?,
          ChapterTranslate*)>

<!ELEMENT SegmentUID (#PCDATA)>
<!ELEMENT NextSegmentUID (#PCDATA)>
<!ELEMENT PreviousSegmentUID (#PCDATA)>
<!ELEMENT SegmentFamily (#PCDATA)>
<!ELEMENT SegmentFilename (#PCDATA)>
<!ELEMENT NextSegmentFilename (#PCDATA)>
<!ELEMENT PreviousSegmentFilename (#PCDATA)>

<!ELEMENT ChapterTranslate (
          ChapterTranslateEditionUID,
          ChapterTranslateCodec,
          ChapterTranslateID)>

<!ELEMENT ChapterTranslateEditionUID (#PCDATA)>
<!ELEMENT ChapterTranslateCodec (#PCDATA)>
<!ELEMENT ChapterTranslateID (#PCDATA)>

=== nmaier/mkvtoolnix/tests/unit/data/text/segmentinfo-valid.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE Info SYSTEM "matroskasegmentinfo.dtd">

<Info>
  <SegmentUID format="hex">00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F</SegmentUID>
  <NextSegmentUID format="hex">ff ee dd cc bb aa 99 88 77 66 55 44 33 22 11 00</NextSegmentUID>
  <PreviousSegmentUID format="hex">00 11 22 33 44 55 66 77 88 99 aa bb cc dd ee ff</PreviousSegmentUID>
  <SegmentFamily format="hex">11 00 11 11 11 22 11 33 11 44 11 55 11 66 11 77</SegmentFamily>
  <ChapterTranslate>
    <ChapterTranslateEditionUID>198273192783</ChapterTranslateEditionUID>
    <ChapterTranslateCodec>0988908</ChapterTranslateCodec>
    <ChapterTranslateID>123123</ChapterTranslateID>
  </ChapterTranslate>
  <SegmentFilename>seg FN</SegmentFilename>
  <PreviousSegmentFilename>previous segment filename</PreviousSegmentFilename>
  <NextSegmentFilename>next segment filename</NextSegmentFilename>
</Info>
